routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/


Route::get('/', 'OrganizationController@create');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/term', 'TermController@index')->name('term');

Route::get('/admin/download/qr/{organization}', 'AdminController@download_qr')->name('admin.download');

Route::get('/paid', 'PaymentController@paid')->name('paid');
Route::post('/response', 'PaymentController@itn')->name('itn');
Route::get('/cancel', 'PaymentController@cancel')->name('cancel');

Auth::routes();

Route::post('capture/visit/{organization}', 'VisitorController@captureVisit')->name('capture.visit');
Route::post('visit/{organization}', 'VisitorController@store')->name('visit.store');
Route::resource('organization', 'OrganizationController');
Route::get('organization/activate/{organization}', 'OrganizationController@welcome')->name('organization.activate');
Route::get('{organization}', 'QuestionController@home')->name('enter');
Route::get('/request/cancel', 'OrganizationController@cancel')->name('organization.cancel');
Route::get('questions/{organization}', 'QuestionController@questions')->name('questions');
Route::post('answer/store/{organization}', 'QuestionController@answers')->name('answers.store');
Route::get('exit/{organization}', 'QuestionController@exit')->name('exit');
Route::get('denied/{organization}', 'QuestionController@denied')->name('denied');
Route::get('forms/{organization}', 'FormController@index')->name('forms.index');
Route::Post('forms/{organization}', 'FormController@store')->name('forms.store');
Route::get('forms/{organization}/{form_id}/edit', 'FormController@edit')->name('forms.edit');
Route::post('forms/{form}/update', 'FormController@update')->name('forms.update');
Route::get('forms/{form}/delete', 'FormController@destroy')->name('forms.delete');
Route::get('user/logout', 'UserController@logout')->name('user.logout');
Route::resource('user', 'UserController');
Route::resource('address', 'AddressController');

Route::get('admin/index', 'AdminController@index')->name('admin.index')->middleware('auth');
Route::get('admin/customize', 'AdminController@customize')->name('admin.customize')->middleware('auth');
Route::post('admin/customize/store', 'AdminController@customize_store')->name('admin.customize_store')->middleware('auth');
Route::get('admin/analytics', 'AdminController@analytics')->name('admin.analytics')->middleware('auth');
Route::get('admin/barcode', 'AdminController@barcode')->name('admin.barcode')->middleware('auth');
Route::post('/admin/config', 'ConfigController@update')->name('admin.config');


Route::post('/member', 'UserController@member')->name('member.create');

Route::get('/process/payment/{user_id}', 'PaymentController@confirmPayment')->name('pay_page');

app/Organization.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Organization extends Model
{
    protected $table = 'organization';

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function address()
    {
        return $this->belongsTo(Address::class, 'address_id');
    }

}

app/Http/Controllers/OrganizationController.php
<?php

namespace App\Http\Controllers;

use App\Mail\WelcomeOrganization;
use App\Mail\CancelMail;
use App\Organization;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Intervention\Image\Facades\Image;
use App\Config;
use App\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Auth;

class OrganizationController extends Controller
{
    public function __construct(){
        $this->middleware('auth', ['except' => ['create', 'store', 'show', 'welcome']]);
    }

    public function index()
    {
        $organisations = Organization::where('user_id', auth()->id())->get();

        return view('organization.index')->with(['organizations' => $organisations]);

    }

    public function create()
    {
        $organization = Organization::all();
        $organization_count = $organization->count();

        $users = User::all()->pluck('email');

        $parameters = [
            'organization_count' => $organization_count,
            'users' => $users
        ];

        return view('organization.create')->with($parameters);
    }


    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'registration' => 'max:255',
            'vat_number' => 'max:255',
            'user_id' => 'required',
            'address_id' => 'nullable',
            'welcome_message' => 'max:255',
            'logo' => 'image|mimes:jpeg,png,jpg',
            'exit_link' => 'max:255',
            'exit_link_text' => 'max:30',
            'account_active' => 'nullable',
            'terms_accepted' => 'nullable',
        ]);

        $path = storage_path('app/public/organization');
        $organization = new Organization();
        $organization->name = $request->name;
        $organization->registration_number = $request->registration;
        $organization->vat_number = $request->vat_number;
        $organization->user_id = $request->user_id;
        $organization->address_id = $request->address_id;
        $organization->welcome_message = $request->welcome_message;
        $organization->exit_link = $request->exit_link;
        $organization->exit_link_label = $request->exit_link_text;
        $organization->account_active = 1;
        $organization->terms_accepted = now();
        $organization->ip_address = $request->ip();

        if ($request->hasFile('logo')) {
            $request->file('logo')->store('public/organization');
            $image = Image::make($path.'/' . $request->file('logo')->hashName());
            if ($image->height() == $image->width()) {
                $image->resize(350, 200);
                $image->save();
            } else {
                // $blur = Image::make($path.'/' . $request->file('logo')->hashName())->fit(200, 200);

                // $image->resize(200, 200, function ($c) {
                //     $c->aspectRatio();
                //     $c->upsize();
                // });

                // $blur->insert($image, 'center');
                // $blur->save();
                $image->resize(350, 200);
                $image->save();
            }

            $organization->logo = $request->file('logo')->hashName();
        }

        $organization->save();

        $config = new Config();
        $config->user_id = $request->user_id;
        $config->office_id = $organization->id;
        $config->logo = '';
        $config->text = 'rgb(0,0,0)';
        $config->background = 'rgb(255,255,255)';
        $config->menu = '';

        $config->save();

        try {
            Mail::to($organization->user->email)->send(new WelcomeOrganization($organization));
        } catch (\Exception $exception){

        }



        // return redirect()->route('organization.show', $organization);
        return redirect()->route('organization.activate', $organization);
    }

    public function show(Organization $organization)
    {
        $date = Carbon::parse(now())->format('ymdHis');
        $merchant = '10013304';
        $version = 'v1';

        $data = [
            'merchant-id' => $merchant,
            'version' => $version,
            'timestamp' => $date,
        ];

        $signature = app('App\Http\Controllers\PaymentController')->generateSignature($data);

        return view('organization.show')->with(['organization' => $organization->load('user', 'address')])->with('date', $date)->with('signature', $signature);
    }

    public function edit(Organization $organization)
    {
        return view('organization.edit')->with(['organization' => $organization]);
    }

    public function update(Request $request, Organization $organization)
    {
        $path = storage_path('app/public/organization');

        $organization->name = $request->name;
        $organization->registration_number = $request->registration;
        $organization->vat_number = $request->vat_number;
        $organization->user_id = $request->user_id;
        $organization->address_id = $request->address_id;
        $organization->welcome_message = $request->welcome_message;
        $organization->exit_link = $request->exit_link;
        $organization->exit_link_label = $request->exit_link_text;
        $organization->account_active = 0;
        //$organization->terms_accepted = now();
        $organization->ip_address = $request->ip();

        if ($request->hasFile('logo')) {
            $request->file('logo')->store('public/organization');
            $image = Image::make($path.'/' . $request->file('logo')->hashName());
            if ($image->height() == $image->width()) {
                $image->resize(350, 200);
                $image->save();
            } else {
                // $blur = Image::make($path.'/' . $request->file('logo')->hashName())->fit(200, 200)->blur();

                // $image->resize(200, 200, function ($c) {
                //     $c->aspectRatio();
                //     $c->upsize();
                // });

                // $blur->insert($image, 'center');
                // $blur->save();

                $image->resize(350, 200);
                $image->save();
            }

            $organization->logo = $request->file('logo')->hashName();
        }

        $organization->save();

        return redirect()->route('organization.show', $organization);
    }


    public function destroy(Organization $organization)
    {
        $organization->delete();

        return redirect()->back();
    }

    public function welcome(Organization $organization)
    {
        $organization->account_active = 1;
        $organization->save();

        return view('organization.account-activated')->with(['organization' => $organization]);
    }

    function cancel() {

        $user = Auth::user();
        $user->purchase_status = 'trial';
        $user->save();

        $organization = Organization::where('user_id', $user->id)->first();

        try {
            Mail::to('support@blackboardbs.com')->send(new CancelMail($user));
        } catch (\Exception $exception){

        }

        // $merchant_id = 10013304;
        // $version = 'v0.3.2';
        // $timestamp = Carbon::now()->toDateTimeString();
        // $passphrase = 'sand3bOxPass';
        // $signature = Hash::make($merchant_id.$version.$timestamp.$passphrase);

        // return redirect('https://api.payfast.co.za/'.$merchant_id.'-'.$version.'-'.$timestamp.'-'.$signature.'/cancel');
        return view('cancel')->with('organization', $organization);
    }
}

resources/views/organization/account-activated.blade.php
@extends('layouts.app')

@section('content')

    <div class="container" style="align-content: center;">
        <div class="text-center" >
            <div class="alert alert-success">
                Thank you for creating your account. Your visitors can visit the provided link or scan the QR code below.
                <a href="{{route('enter', $organization)}}" >{{route('enter', $organization)}}</a>
                
            </div>

            <p></p>
            <a style="display: block; width: 25%;" href="{{route('forms.index', $organization)}}" class="btn btn-success">Customize Your Questions</a>
            <br>
            <a style="display: block; width: 25%;" href="{{ route('admin.download', $organization) }}" class="btn btn-primary" id="print" name="print">Print QR Code</a>
            {{-- <th>QR Code</th> --}}
            <td>{!! QrCode::size(200)->generate(route('enter', $organization)); !!}</td>
            
            
        </div>
    </div>

@endsection

resources/views/organization/edit.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
<div class="container">
    <h3>Capture An Organization</h3>
    <form action="{{route('organization.update', $organization->id)}}" method="POST"  enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" name="name" class="form-control" id="name" value="{{$organization->name}}">
            </div>
        </div>
        <div class="form-group row">
            <label for="registration" class="col-sm-2 col-form-label">Registration Number/ID Number</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="registration" id="registration"  value="{{$organization->registration_number}}">
            </div>
        </div>
        <div class="form-group row">
            <label for="vat_number" class="col-sm-2 col-form-label">Vat Number</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="vat_number" id="vat_number" value="{{$organization->vat_number}}">
            </div>
        </div>
        <div class="form-group row">
            <label for="user" class="col-sm-2 col-form-label">Capture User</label>
            <div class="col-sm-10" id="user_field">
                <input type="text" readonly class="form-control-plaintext" id="staticEmail" value="{{$organization->user->name??''}}">
                <input type="hidden" name="user_id" id="user" value="{{$organization->user_id}}">
            </div>
        </div>
        <div class="form-group row">
            <label for="address" class="col-sm-2 col-form-label">Address</label>
            <div class="col-sm-10" id="address_field">
                <input type="button" class="btn btn-sm btn-primary mb-2" id="address" value="Edit Address" data-toggle="modal" data-target="#addressModal">
                <input type="hidden" name="address_id" value="{{$organization->address_id}}">
                <ul class="list-group">
                    <li class="list-group-item">{{$organization->address->address_line1??''}}</li>
                    @isset($organization->address->address_line2)
                        <li class="list-group-item">{{$organization->address->address_line2??''}}</li>
                    @endisset
                    @isset($organization->address->suburb)
                        <li class="list-group-item">{{$organization->address->suburb??''}}</li>
                    @endisset
                    @isset($organization->address->city)
                        <li class="list-group-item">{{$organization->address->city??''}}</li>
                    @endisset
                    @isset($organization->address->province)
                        <li class="list-group-item">{{$organization->address->province??''}}</li>
                    @endisset
                    @isset($organization->address->country)
                        <li class="list-group-item">{{$organization->address->country??''}}</li>
                    @endisset
                    @isset($organization->address->zip_code)
                        <li class="list-group-item">{{$organization->address->zip_code??''}}</li>
                    @endisset
                </ul>
            </div>
        </div>
        <div class="form-group row">
            <label for="welcome_message" class="col-sm-2 col-form-label">Welcome Message</label>
            <div class="col-sm-10">
                <textarea name="welcome_message" class="form-control" id="welcome_message" rows="3">{{$organization->welcome_message}}</textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="logo" class="col-sm-2 col-form-label">Logo</label>
            <div class="col-sm-10">
                <img src="{{asset('storage/organization/'.$organization->logo)}}" class="img-thumbnail">
                <input type="file" name="logo" class="form-control-file" id="logo">
            </div>
        </div>
        <div class="form-group row">
            <label for="exit_link" class="col-sm-2 col-form-label">Exit Link (Your url)</label>
            <div class="col-sm-10">
                <input type="text" name="exit_link" class="form-control" id="exit_link" value="{{$organization->exit_link}}">
            </div>
        </div>
        <div class="form-group row">
            <label for="exit_link_text" class="col-sm-2 col-form-label">Exit Link Label</label>
            <div class="col-sm-10">
                <input type="text" name="exit_link_text" class="form-control" id="exit_link_text" value="{{$organization->exit_link_label}}">
            </div>
        </div>
        {{--<div class="form-group form-check text-center">
            <input type="checkbox" name="accept_terms" class="form-check-input" id="accept_terms" value="1">
            <label class="form-check-label" for="accept_terms">Accept Terms and Conditions</label>
        </div>--}}
        <div class="text-center">
            <button type="submit" class="btn btn-primary" id="capture-organisation">Update Organization</button>
        </div>
    </form>
    <!-- Address Modal -->
    <div class="modal fade" id="addressModal" tabindex="-1" aria-labelledby="addressModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="addressModalLabel">Edit Address</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="address_line1">Address Line 2</label>
                        <input type="text" class="form-control" id="address_line1" value="{{$organization->address->address_line1??''}}">
                    </div>
                    <div class="form-group">
                        <label for="address_line2">Address Line 1</label>
                        <input type="text" class="form-control" id="address_line2" value="{{$organization->address->address_line2??''}}">
                    </div>
                    <div class="form-group">
                        <label for="suburb">Suburb</label>
                        <input type="text" class="form-control" id="suburb"  value="{{$organization->address->suburb??''}}">
                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" class="form-control" id="city" value="{{$organization->address->suburb??''}}">
                    </div>
                    <div class="form-group">
                        <label for="province">Province/State</label>
                        <input type="text" class="form-control" id="province" value="{{$organization->address->province??''}}">
                    </div>
                    <div class="form-group">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" id="country" value="{{$organization->address->country??''}}">
                    </div>
                    <div class="form-group">
                        <label for="zip_code">Zip Code</label>
                        <input type="text" class="form-control" id="zip_code" value="{{$organization->address->zip_code??''}}">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="capture-address">Update Address</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    $(function (){
        $("#capture-address").on('click', function (){
            let addressLine1 = $("#address_line1");
            if (addressLine1.val().length < 1){
                addressLine1.css('border', '1px solid red')
                    .after('<div class="text-danger">Address Line 1 is required</div>');
            }

            axios.patch('{{route('address.update', $organization->address_id)}}', {
                addressLine1: addressLine1.val(),
                addressLine2: $("#address_line2").val(),
                suburb: $("#suburb").val(),
                city: $("#city").val(),
                province: $("#province").val(),
                country: $("#country").val(),
                zipCode: $("#zip_code").val(),
            })
                .then(function (response) {
                    let listBuilder = '<li class="list-group-item">'+response.data.address.address_line1+'</li>';
                    if (response.data.address.address_line2 != null) listBuilder += '<li class="list-group-item">'+response.data.address.address_line2+'</li>'
                    if (response.data.address.suburb != null) listBuilder += '<li class="list-group-item">'+response.data.address.suburb+'</li>'
                    if (response.data.address.city != null) listBuilder += '<li class="list-group-item">'+response.data.address.city+'</li>'
                    if (response.data.address.province != null) listBuilder += '<li class="list-group-item">'+response.data.address.province+'</li>'
                    if (response.data.address.country != null) listBuilder += '<li class="list-group-item">'+response.data.address.country+'</li>'
                    if (response.data.address.zip_code != null) listBuilder += '<li class="list-group-item">'+response.data.address.zip_code+'</li>'
                    $(".list-group").replaceWith(
                        '<ul class="list-group">' +
                        listBuilder +
                        '</ul>' +
                        '<input type="hidden" name="address_id" value="'+ response.data.address.id+'">'
                    )

                    $("#addressModal").modal('hide');
                    console.log(response);
                })
                .catch(function (error) {
                    console.log(error);
                })
        })
    })
</script>
</body>
</html>

resources/views/organization/index.blade.php
@extends('layouts.app')

@section('extra-css')
    


@endsection

@section('content')
    <div class="container">
        <h3>View Organizations <a href="{{route('organization.create')}}" class="float-right btn btn-sm btn-primary">Add Organization</a></h3>
        <table class="table table-sm table-striped">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Registration Number</th>
                <th scope="col">Contact Person</th>
                <th scope="col">Contact Number</th>
                <th scope="col">Contact Email</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @forelse($organizations as $organization)
                <tr>
                    <td scope="row"><a href="{{route('organization.show', $organization->id)}}">{{$organization->name}}</a></td>
                    <td>{{$organization->registration_number}}</td>
                    <td>{{$organization->user->name??''}}</td>
                    <td>{{$organization->user->contact_number??''}}</td>
                    <td>{{$organization->user->email??''}}</td>
                    <td>
                        <a href="{{route('organization.edit', $organization->id)}}" class="btn btn-sm btn-success">Edit</a>
                        <form action="{{route('organization.destroy', $organization->id)}}" method="post">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="6">No organizations yet</td>
                </tr>
            @endforelse
            </tbody>
        </table>
    </div>

@endsection

resources/views/organization/show.blade.php
@extends('layouts.app')

@section('extra-css')



@endsection

@section('content')
<div class="container-fluid" style="margin-top: 2%; display: inline-block;">
    <div class="row">
    @include('layouts.admin-menu')
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10" style="border-style: groove; padding:2%; margin:2%;">
        <h3><strong>Organization Profile</strong></h3>
        <span>View and edit your organization here.</span>
        <div class="custom" style="margin-top: 2%;">
            
            
        
    {{-- <div class="alert alert-info">
        You will recieve an email where you can activate your organization
    </div> --}}
    @auth
        @if (Auth()->user()->id == $organization->user_id)
            
        @endif
    @else 
        <div class="alert alert-info">
            You will recieve an email where you can activate your organization
        </div>
    @endauth
    {{-- <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10" style="float:right; padding:2%; margin:2%;"> --}}
        <div class="text-center" style="margin-bottom: 2%;">
            <a href="{{route('enter', $organization)}}" class="btn btn-info mr-3">Visitor Screen</a>
            <a href="{{route('forms.index', $organization)}}" class="btn btn-primary">Customize Your Questions</a>
            <a href="{{route('organization.edit', $organization)}}" class="btn btn-success ml-3">Edit</a>
        </div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th colspan="4" class="text-center">Organization</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">Organization Name</th>
                <td>{{$organization->name}}</td>
                <th>Registration Number/ID Number</th>
                <td>{{$organization->registration_number}}</td>
            </tr>
            <tr>
                <th scope="row">Vat Number</th>
                <td>{{$organization->vat_number}}</td>
                <td>Contact Person</td>
                <td>{{$organization->user->name??''}}</td>
            </tr>
            <tr>
                <th scope="row">Billing Address</th>
                <td colspan="3"><ul class="list-group">
                        <li class="list-group-item">{{$organization->address->address_line1??''}}</li>
                        @isset($organization->address->address_line2)
                            <li class="list-group-item">{{$organization->address->address_line2??''}}</li>
                        @endisset
                        @isset($organization->address->suburb)
                            <li class="list-group-item">{{$organization->address->suburb??''}}</li>
                        @endisset
                        @isset($organization->address->city)
                            <li class="list-group-item">{{$organization->address->city??''}}</li>
                        @endisset
                        @isset($organization->address->province)
                            <li class="list-group-item">{{$organization->address->province??''}}</li>
                        @endisset
                        @isset($organization->address->country)
                            <li class="list-group-item">{{$organization->address->country??''}}</li>
                        @endisset
                        @isset($organization->address->zip_code)
                            <li class="list-group-item">{{$organization->address->zip_code??''}}</li>
                        @endisset
                    </ul></td>
            </tr>
            <tr>
                <td>Exit Link</td>
                <td>{{$organization->exit_link??''}}</td>
                <th scope="row">Exit Link Label</th>
                <td>{{$organization->exit_link_label}}</td>

            </tr>
            <tr>
                <th scope="row">Welcome Message</th>
                <td colspan = 3>{{$organization->welcome_message}}</td>
            </tr>
            <tr>
                <th>Organization Logo</th>
                <td><img src="{{asset('storage/organization/'.$organization->logo)}}" alt="{{$organization->name}}" class="img-thumbnail"></td>
                <th>QR Code</th>
                <td>{!! QrCode::size(200)->generate(route('enter', $organization)); !!}
                    <a href="{{ route('admin.download', $organization) }}" class="btn btn-primary" id="print" name="print">Print QR Code</a></td>
            </tr>
            </tbody>
        </table>
        @auth
        @if (Auth()->user()->id == $organization->user_id && Auth()->user()->purchase_status == 'purchased')
            {{-- To cancel your subscription <a href="{{ route('cancel') }}">click here</a>. --}}
            To cancel your subscription <a href="{{ route('organization.cancel') }}">click here</a>.
            <br>
            <small>Note: This will revoke your access to the Covid App immediately</small>
            {{-- <form action="https://api.payfast.co.za/subscriptions/dc0521d3-55fe-269b-fa00-b647310d760f/cancel" method="post">
                <input type="hidden" name="merchant-id" value="10013304">
                <input type="hidden" name="version" value="v1">
                <input type="hidden" name="timestamp" value="{{ $date }}">
                <input type="hidden" name="signature" value="{{ $signature }}">
                <button class="btn btn-danger">Cancel</button>
            </form> --}}
        @endif
        @endauth
    </div>
</div>
</div>
    {{-- </div> --}}
</div>

@endsection